import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class RecetarioCarmelitaService {
  recetas: any=[
    {
      img: '../../../assets/img/recetas-carmelita/malteada-rompope.png',
      nombre:'Malteada Rompopera',
      descripcion:'Deliciosa malteada de vainilla con Rompope Carmelita',
      alt:'Imagen de malteada de vainilla con Rompope Carmelita',
      linkVideo: 'https://www.youtube.com/watch?v=BtXwWCpRz3I',
      ingrediente1: ' 1.- ½ taza de Rompope Carmelita',
      ingrediente2: ' 2.- 2 bolitas de helado de vainilla',
      ingrediente3: ' 3.- 1 taza de leche de almendra',
      pr1: '1.- Vaciar la ½ taza de rompope a la licuadora.',
      pr2: '2.- Añadir las bolitas de helado de vainilla.',
      pr3: '3.- Licuamos durante 30seg.',
      pr4: '4.- Servimos y a disfrutar.',
      galeria1: '.../../../assets/img/galeria-recetas/malteada/1.png',
      galeriaalt1: "Imagen de la preparación de la malteada rompopera 1",
      galeria2: '.../../../assets/img/galeria-recetas/malteada/2.png',
      galeriaalt2: "Imagen de la preparación de la malteada rompopera 2",
      galeria3: '.../../../assets/img/galeria-recetas/malteada/3.png',
      galeriaalt3: "Imagen de la preparación de la malteada rompopera 3",
      galeria4: '.../../../assets/img/galeria-recetas/malteada/4.png',
      galeriaalt4: "Imagen de la preparación de la malteada rompopera 4",
      galeria5: '.../../../assets/img/galeria-recetas/malteada/5.png',
      galeriaalt5: "Imagen de la preparación de la malteada rompopera 5",
      galeria6: '.../../../assets/img/galeria-recetas/malteada/6.png',
      galeriaalt6: "Imagen de la preparación de la malteada rompopera 6",
      galeria7: '.../../../assets/img/galeria-recetas/malteada/7.png',
      galeriaalt7: "Imagen de la preparación de la malteada rompopera 7",
      galeria8: '.../../../assets/img/galeria-recetas/malteada/8.png',
      galeriaalt8: "Imagen de la preparación de la malteada rompopera 8",

    },
    {
      img: '../../../assets/img/recetas-carmelita/gelatina-rompope.png',
      nombre:'Gelatina Carmelita.',
      descripcion:'Deliciosa gelatina de Rompope Carmelita',
      alt:'Imagen de la gelatina de Rompope Carmelita',
      linkVideo: 'https://www.youtube.com/watch?v=4W-IcN4urkk',
      ingrediente1: ' 1.- 1 ½ taza de Rompope Carmelita',
      ingrediente2: ' 2.- 2 cucharadas soperas de grenetina',
      ingrediente3: ' 3.- 1 taza de agua fría',
      ingrediente4: ' 4.- Mantequilla',
      ingrediente5: ' 5.- ½ taza de agua fría',
      ingrediente6: ' 6.- 1 taza de azúcar',
      pr1: '1.- Colocamos en un recipiente la taza de agua',
      pr2: '2.- Posteriormente ponemos la grenetina en el recipiente de agua y movemos bien.',
      pr3: '3.- Colocamos 2 tazas de agua en otro recipiente y agregamos la taza de azúcar,  se pone a la lumbre hasta que hierva. .',
      pr4: '4.- Una vez que hierve se le pone la grenetina y movemos para que se disuelva bien.',
      pr5: '5.- Vamos preparando el molde donde pondremos la mezcla de agua, grenetina y azucar. En donde untaremos un poco de mantequilla antes de colocar (esto para que no se pegue)',
      pr6: '6.- Una vez ya fría la mezcla, colocamos el rompope y mezclamos.',
      pr7: '7.- Colocamos todo en el molde, una vez mezclado todo y metemos al refrigerador.',
      pr8: '8.- Dejamos en el refrigerador unas cuantas horas.',
      pr9: '9.- Sacamos del molde y a disfrutar.',
      galeria1: '.../../../assets/img/galeria-recetas/gelatina/1.png',
      galeriaalt1: "Imagen de la preparación de la gelatina Carmelita 1",
      galeria2: '.../../../assets/img/galeria-recetas/gelatina/2.png',
      galeriaalt2: "Imagen de la preparación de la gelatina Carmelita 2",
      galeria3: '.../../../assets/img/galeria-recetas/gelatina/3.png',
      galeriaalt3: "Imagen de la preparación de la gelatina Carmelita 3",
      galeria4: '.../../../assets/img/galeria-recetas/gelatina/4.png',
      galeriaalt4: "Imagen de la preparación de la gelatina Carmelita 4",
      galeria5: '.../../../assets/img/galeria-recetas/gelatina/5.png',
      galeriaalt5: "Imagen de la preparación de la gelatina Carmelita 5",
      galeria6: '.../../../assets/img/galeria-recetas/gelatina/6.png',
      galeriaalt6: "Imagen de la preparación de la gelatina Carmelita 6",
      galeria7: '.../../../assets/img/galeria-recetas/gelatina/7.png',
      galeriaalt7: "Imagen de la preparación de la gelatina Carmelita 7",
      galeria8: '.../../../assets/img/galeria-recetas/gelatina/8.png',
      galeriaalt8: "Imagen de la preparación de la gelatina Carmelita 8",
    },
    {
      img: '../../../assets/img/recetas-carmelita/pastel3leches-rompope.png',
      nombre:'Pastel Rompopero',
      descripcion:'Delicioso pastel de 3 leches',
      alt:'Imagen del delicioso pastel de 3 leches',
      linkVideo: 'https://www.facebook.com/RompopeCarmelita/posts/2145649825579479',
      ingrediente1: '1.- 5 claras de huevo',
      ingrediente2: '2.- ¾  tazas de azúcar, para las claras',
      ingrediente3: '3.- 5 yemas de huevo',
      ingrediente4: '4.- ¾  tazas de azúcar, para las yemas',
      ingrediente5: '5.- ½  tazas de leche de vaca',
      ingrediente6: '6.- 1 cucharadita de vainilla líquida',
      ingrediente7: '7.- 1 cucharadita de ralladura de limón',
      ingrediente8: '8.- 1 ½  tazas de harina',
      ingrediente9: '9.- 1 cucharadita de polvo para hornear',
      ingrediente10: '10.- 1 taza de leche condensada, para las tres leches',
      ingrediente11: '11.- 1 taza de leche evaporada, para las tres leches',
      ingrediente12: '12.- 1 taza de leche entera, para las tres leches',
      ingrediente13: '13.- ¼  tazas de rompope, para las tres leches',
      ingrediente14: '14.- 2 tazas de crema batida',
      ingrediente15: '15.- al gusto de fresa, para decorar',
      ingrediente16: '16.- al gusto de menta, para decorar',
      pr1: '1.- Precalienta el horno a 180°C.',
      pr2: '2.- Para el pastel, bate las claras con el azúcar a punto de turrón.',
      pr3: '3.- Bate las yemas con el azúcar hasta que cambien de color, agrega poco a poco la leche, la vainilla y los ingredientes secos, con ayuda de un colador.',
      pr4: '4.- Agrega de manera envolvente las claras a la mezcla anterior.',
      pr5: '5.- Vierte la preparación en dos moldes para pastel, previamente engrasados y enharinados, hornea por 25 minutos. Deja enfriar y reserva.',
      pr6: '6.- Para las tres leches, mezcla la leche condensada, la leche evaporada, la leche entera y el rompope.',
      pr7: '7.- Con ayuda de un tenedor pica un bizcocho y vierte las tres leches, refrigera 1 hora, coloca crema batida sobre el bizcocho, coloca encima el otro bizcocho, pica con un tenedor y con ayuda de una brocha moja de tres leches.',
      pr8: '8.- Con ayuda de una espátula cubre el pastel con la crema batida restante, decora con fresas y menta.',
      galeria1: '.../../../assets/img/galeria-recetas/melon-sandia/1.png',
      galeriaalt1: "Imagen de las chicas de Melón y Sandía haciendo el Pastel Rompopero 1",
      galeria2: '.../../../assets/img/galeria-recetas/melon-sandia/2.png',
      galeriaalt2: "Imagen de las chicas de Melón y Sandía haciendo el Pastel Rompopero 2",
      galeria3: '.../../../assets/img/galeria-recetas/melon-sandia/3.png',
      galeriaalt3: "Imagen de las chicas de Melón y Sandía haciendo el Pastel Rompopero 3",
      galeria4: '.../../../assets/img/galeria-recetas/melon-sandia/4.png',
      galeriaalt4: "Imagen de las chicas de Melón y Sandía haciendo el Pastel Rompopero 4",
      galeria5: '.../../../assets/img/galeria-recetas/melon-sandia/5.png',
      galeriaalt5: "Imagen de las chicas de Melón y Sandía haciendo el Pastel Rompopero 5",
      galeria6: '.../../../assets/img/galeria-recetas/melon-sandia/6.png',
      galeriaalt6: "Imagen de las chicas de Melón y Sandía haciendo el Pastel Rompopero 6",
      galeria7: '.../../../assets/img/galeria-recetas/melon-sandia/7.png',
      galeriaalt7: "Imagen de las chicas de Melón y Sandía haciendo el Pastel Rompopero 7",
      galeria8: '.../../../assets/img/galeria-recetas/melon-sandia/8.png',
      galeriaalt8: "Imagen de las chicas de Melón y Sandía haciendo el Pastel Rompopero 8",
    },
    {
      img: '../../../assets/img/recetas-carmelita/pastelcrepas-rompope.png',
      nombre:`PASTEL CREPAS CARMELITA`,
      descripcion:'Delicioso pastel de crepas',
      alt:'Imagen del delicioso pastel de crepas',
      linkVideo: 'https://www.youtube.com/watch?v=SsiUKH7MH08',
      ingrediente1: '2 tazas de leche de vaca',
      ingrediente2: '1 taza de harina',
      ingrediente3: '1/4 de taza de mantequilla fundida',
      ingrediente4: '2 huevos',
      ingrediente5: '1/8 de taza de azúcar',
      ingrediente6: '1 cucharadita de vainilla líquida',
      ingrediente7: '1 cucharadita de canela en polvo',
      ingrediente8: '3 tazas de crema para batir',
      ingrediente9: '3 cucharadas de ralladura de limón amarillo',
      ingrediente10: '3 tazas de fresa, cortadas en láminas',
      pr1: '1.- En un bowl mezcla todos los ingredientes de las crepas hasta formar un mezcla homogénea.',
      pr2: '2.- Calienta una sartén a fuego medio y forma crepas hasta conseguir el número de crepas deseadas para las capas del pastel.',
      pr3: '3.- En un bowl bate la crema para batir hasta que doble su volumen, agrega la ralladura de limón, el jugo de limón y el azúcar glass.',
      pr4: '4.- En un plato coloca una crepa de base, unta una capa de crema batida y agrega fresas. Repite hasta formar varias capas.',
      pr5: '5.- Cubre todo el pastel con crema batida, decora la parte de arriba con abundantes fresas. Refrigera 1 hora, sirve y disfruta.',
      galeria1: '.../../../assets/img/galeria-recetas/chef-oliver/1.png',
      galeriaralt1: "Imágenes del chef Oliver y Pastel de Crepas 1",
      galeria2: '.../../../assets/img/galeria-recetas/chef-oliver/2.png',
      galeriaalt2: "Imágenes del chef Oliver y Pastel de Crepas 2",
      galeria3: '.../../../assets/img/galeria-recetas/chef-oliver/3.png',
      galeriaalt3: "Imágenes del chef Oliver y Pastel de Crepas 3",
      galeria4: '.../../../assets/img/galeria-recetas/chef-oliver/4.png',
      galeriaalt4: "Imágenes del chef Oliver y Pastel de Crepas 4",
      galeria5: '.../../../assets/img/galeria-recetas/chef-oliver/5.png',
      galeriaalt5: "Imágenes del chef Oliver y Pastel de Crepas 5",
      galeria6: '.../../../assets/img/galeria-recetas/chef-oliver/6.png',
      galeriaalt6: "Imágenes del chef Oliver y Pastel de Crepas 6",
      galeria7: '.../../../assets/img/galeria-recetas/chef-oliver/7.png',
      galeriaalt7: "Imágenes del chef Oliver y Pastel de Crepas 7",
      galeria8: '.../../../assets/img/galeria-recetas/chef-oliver/8.png',
      galeriaalt8: "Imágenes del chef Oliver y Pastel de Crepas 8",
      
    } 
      
  ]
  constructor() { }
  obtenerReceta(){
    return this.recetas;
  }
  obtenerUno(i){
    return this.recetas[i];
  }
}
